var gulp = require("gulp");
var bower = require("gulp-bower");
var elixir = require("laravel-elixir");

gulp.task('bower', function() {
    return bower();
});

var paths = {
    'jquery': 'vendor/jquery-legacy/dist',
    'dropify': 'vendor/dropify/dist',
    'fontawesome': 'vendor/font-awesome'
};

// отключаем генерацию sourcemaps
elixir.config.sourcemaps = false;

elixir(function (mix) {

    // запускаем bower и подтягиваем все необходимые зависимости
    mix.task('bower');

    // копируем шрифты в public/fonts
    mix.copy('resources/' + paths.bootstrap + '/fonts/bootstrap/**', 'public/fonts');
    mix.copy('resources/' + paths.fontawesome + '/fonts/**', 'public/fonts');
    mix.copy('resources/' + paths.dropify + '/fonts/**', 'public/build/fonts');


    // Компилируем sass файлы и сохраняем результат в директорию resources/css
    mix.sass(['app.scss', 'mobile.scss'], 'resources/css', {
        includePaths: [
            'resources/' + paths.bootstrap + '/stylesheets/',
            'resources/' + paths.bootswatch + '/',
            'resources/' + paths.fontawesome + '/scss/'
        ]
    });

    // объединяем все CSS
    mix.styles([
        //'UIstyle.min.css',
        'css/sweetalert.css',
        'resources/' + paths.dropify + '/css/dropify.min.css',
        'css/app.css' // app.css is generated by sass and has some overrides
    ], 'public/css/app.css', 'resources/');

    // Объединяем скрипты
    mix.scripts([
        paths.jquery + '/jquery.js',
        'js/materialize.js',
        'js/jquery.validate.js',
        'js/jquery.formatter.js',
        'js/sweetalert-dev.js',
        'resources/' + paths.dropify + '/js/dropify.min.js',
        'js/main.js' // Пользовательские скрипты

    ], 'public/js/app.js', 'resources/');

    // генерируем файлы с уникальным именем, чтобы исключить кеширование на клиенте
    mix.version([
        'public/css/app.css',
        'public/js/app.js'
    ]);
});

